base:
  config:
    tidb:
      hostname: tidb.demo.com
      port: 4000
    mysql:
      hostname: mysql.demo.com
      port: 3306
    nacos:
      hostname: nacos.demo.com
      port: 80

spring:
  application:
    name: training-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.mysql.hostname}:${base.config.mysql.port}/hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

dubbo:
  scan:
    base-packages: com.demo.hotel.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

mybatis:
  type-aliases-package: com.demo.hotel.provider.domain
  mapper-locations: classpath:mapper/*.xml